# Generated by Django 5.0 on 2023-12-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diesel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=10, null=True)),
                ('paid_person_name', models.CharField(blank=True, max_length=30, null=True)),
                ('petrol_bunk_name', models.CharField(blank=True, max_length=100, null=True)),
                ('petrol_bunk_address', models.TextField()),
                ('starting_KM', models.CharField(blank=True, max_length=30, null=True)),
                ('closing_KM', models.CharField(blank=True, max_length=30, null=True)),
                ('diesel_filled', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'diesel',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=12)),
                ('alternative_contact', models.CharField(max_length=12)),
                ('licence_number', models.CharField(max_length=30)),
                ('licence_expired_date', models.DateField(blank=True, null=True)),
                ('driver_joining_date', models.DateField(blank=True, null=True)),
                ('driver_resigned_date', models.DateField(blank=True, null=True)),
                ('driver_incharge', models.CharField(max_length=255)),
                ('driver_image', models.ImageField(upload_to='driver')),
                ('driver_license_image', models.ImageField(blank=True, null=True, upload_to='driver')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('electrical_bill_upload', models.ImageField(upload_to='electrical')),
            ],
            options={
                'db_table': 'electrical',
            },
        ),
        migrations.CreateModel(
            name='Fitness_Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('fc_renewal_officer_name', models.CharField(max_length=255)),
                ('fitness_from_date', models.DateTimeField(blank=True, null=True)),
                ('fitness_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_image', models.ImageField(upload_to='fc')),
            ],
            options={
                'db_table': 'fitness_certificate',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_register_no', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(blank=True, max_length=12, null=True)),
                ('paid_person', models.CharField(blank=True, max_length=255, null=True)),
                ('bunk_name', models.CharField(blank=True, max_length=255, null=True)),
                ('petrol', models.CharField(blank=True, max_length=12, null=True)),
                ('diesel', models.CharField(blank=True, max_length=12, null=True)),
                ('amount', models.CharField(blank=True, max_length=12, null=True)),
                ('bill_upload', models.ImageField(upload_to='fuel')),
            ],
            options={
                'db_table': 'fuel',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insurance_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=155, null=True)),
                ('policy_start_date', models.DateTimeField(blank=True, null=True)),
                ('policy_expired_date', models.DateTimeField(blank=True, null=True)),
                ('check_number', models.CharField(max_length=50)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'insurance',
            },
        ),
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=10, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=30, null=True)),
                ('incharge_name', models.CharField(blank=True, max_length=30, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('workshop_name', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_upload', models.ImageField(upload_to='maintenance_bill')),
            ],
            options={
                'db_table': 'maintainance',
            },
        ),
        migrations.CreateModel(
            name='Mechanical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('mechanical_bill_upload', models.ImageField(upload_to='mechanical')),
            ],
            options={
                'db_table': 'mechanical',
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=60, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_upload', models.ImageField(upload_to='painting')),
            ],
            options={
                'db_table': 'painting',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_name', models.CharField(blank=True, max_length=40, null=True)),
                ('mode', models.CharField(max_length=20)),
                ('permit_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('permit_A_img_upload', models.ImageField(upload_to='permit a')),
                ('permit_B_img_upload', models.ImageField(upload_to='permit b')),
                ('permit_from_date', models.DateTimeField(auto_now_add=True)),
                ('permit_expired_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permit',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=255)),
                ('vehicle_register_no', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('quotation', models.TextField()),
                ('quotation_date', models.DateTimeField()),
                ('amount', models.CharField(max_length=10)),
                ('quotation_upload_img', models.ImageField(upload_to='quotation')),
            ],
            options={
                'db_table': 'quotation',
            },
        ),
        migrations.CreateModel(
            name='Rc_Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=10, null=True)),
                ('chassis_number', models.CharField(max_length=40)),
                ('engine_number', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(blank=True, max_length=12, null=True)),
                ('vehicle_company', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_year', models.DateTimeField(auto_now_add=True)),
                ('rc_expired_date', models.DateField(blank=True, null=True)),
                ('rc_image', models.ImageField(upload_to='rc_book')),
            ],
            options={
                'db_table': 'rc_book',
            },
        ),
        migrations.CreateModel(
            name='Rto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('mfr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel', models.CharField(blank=True, max_length=255, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=10, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'rto',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_number', models.CharField(max_length=50)),
                ('bank_details', models.TextField()),
                ('vehicle_type', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=10, null=True)),
                ('pondicherry_tax_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('pondicherry_from_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pondicherry_end_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tamilnadu_tax_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('tamilnadu_from_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tamilnadu_end_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tax_copy_image', models.ImageField(upload_to='tax')),
            ],
            options={
                'db_table': 'tax',
            },
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tyre_size_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tyre_size', models.CharField(blank=True, max_length=255, null=True)),
                ('grd', models.CharField(blank=True, max_length=8, null=True)),
                ('type_of_service', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_upload', models.ImageField(upload_to='tyre')),
            ],
            options={
                'db_table': 'tyre',
            },
        ),
        migrations.CreateModel(
            name='BusLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=10, null=True)),
                ('starting_time', models.DateTimeField(auto_now_add=True)),
                ('starting_km', models.CharField(blank=True, max_length=30, null=True)),
                ('from_place', models.CharField(blank=True, max_length=30, null=True)),
                ('end_place', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose_of_journey', models.CharField(blank=True, max_length=30, null=True)),
                ('closing_time', models.DateTimeField(auto_now_add=True)),
                ('closing_km', models.CharField(max_length=30)),
                ('total_km', models.CharField(max_length=30)),
                ('fuel_field', models.CharField(max_length=30)),
                ('remark', models.TextField()),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.driver')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Bus_Route_Details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bus_route_timing', models.DateTimeField(blank=True, null=True)),
                ('bus_co_ordinator', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pro_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('bus_stop', models.CharField(blank=True, max_length=50, null=True)),
                ('time_picking', models.DateTimeField(auto_now_add=True)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.driver')),
                ('rc_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.rc_book')),
            ],
            options={
                'db_table': 'bus_route_details',
            },
        ),
    ]
